name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: List Android directory
      run: ls -l $ANDROID_HOME/build-tools
    - name: Echo env. variable $GITHUB_PATH
      run: echo $GITHUB_PATH
    - name: Exit!!!!!
      run: exit 1

    - name: Set zipalign path
      run: echo "$ANDROID_HOME/build-tools/30.0.3" >> $GITHUB_PATH

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Check project
      run: ./gradlew check

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Download keystore
      run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > keystore.jks

    - name: Sign APK
      run: |
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} app/build/outputs/apk/release/app-release-unsigned.apk ${{ secrets.KEY_ALIAS }}

    - name: Align APK
      run: zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ZOfflineObb
        path: app/build/outputs/apk/release/*
